// 'use server';

/**
 * @fileOverview Generates a poetic, symbolic reflection based on user input,
 * temperament, and soul stage.
 *
 * - generateReflection - A function that generates the reflection.
 * - GenerateReflectionInput - The input type for the generateReflection function.
 * - GenerateReflectionOutput - The return type for the generateReflection function.
 */

'use server';

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReflectionInputSchema = z.object({
  innerState: z
    .string()
    .describe(
      'The user provided inner conflict, question, feeling or contradiction.'
    ),
  temperament: z.enum(['Sanguine', 'Choleric', 'Melancholic', 'Phlegmatic']).describe('The users temperament.'),
  soulStage: z
    .enum(['nafs al-ammarah', 'lawwamah', 'mutma’innah'])
    .describe('The users estimated soul stage.'),
});

export type GenerateReflectionInput = z.infer<typeof GenerateReflectionInputSchema>;

const GenerateReflectionOutputSchema = z.object({
  reflection: z.string().describe('The poetic, symbolic reflection generated by Hikma.'),
  wisdomSeed: z.string().describe('A one-line truth to carry.'),
  dhikr: z.string().optional().describe('An optional dhikr or invocation to anchor the heart.'),
});

export type GenerateReflectionOutput = z.infer<typeof GenerateReflectionOutputSchema>;

export async function generateReflection(
  input: GenerateReflectionInput
): Promise<GenerateReflectionOutput> {
  return generateReflectionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateReflectionPrompt',
  input: {schema: GenerateReflectionInputSchema},
  output: {schema: GenerateReflectionOutputSchema},
  prompt: `You are Hikma, a wise guide that provides poetic and symbolic reflections to users based on their inner state, temperament, and soul stage. Your reflections are not advice but a mirror of meaning to aid in soul purification. Begin and end the conversation with peace, asking questions with symbols, similar to a Rorschach test. Use archetypal images, poetic choices, and metaphor chains to infer temperament and nafs stage.

Inner State: {{{innerState}}}
Temperament: {{{temperament}}}
Soul Stage: {{{soulStage}}}

Generate a reflection that is:
- Poetic and symbolic
- Personalized to the user's temperament and soul stage
- Ends with a wisdom seed (a one-line truth to carry)
- Optionally, includes a dhikr or invocation to anchor the heart
`,
});

const generateReflectionFlow = ai.defineFlow(
  {
    name: 'generateReflectionFlow',
    inputSchema: GenerateReflectionInputSchema,
    outputSchema: GenerateReflectionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
